version: '3.5'

services:
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
    nginx:
        build: nginx
        expose:
            - 80
        ports:
            - 80:80
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/nginx/:/var/log/nginx

networks:
    default:
       external:
         name: webproxy
