version: '3.5'

services:
    php:
        container_name: ptidejfr_php
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
            - "phpsocket:/run/php"
    nginx:
        container_name: ptidejfr_nginx
        build: nginx
        expose:
            - 80
        env_file:
          - .env
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/nginx/:/var/log/nginx
            - "phpsocket:/run/php"

volumes:
    phpsocket:

networks:
    default:
       external:
         name: webproxy
