ptitdej_homepage:
    path:     /
    defaults: { _controller: PtitdejBundle:Default:index }

form_entreprise:
    path:     /formulaire-entreprise
    defaults: { _controller: PtitdejBundle:Default:formulaireEntreprise }


form_prestataire:
    path:     /formulaire-prestataire
    defaults: { _controller: PtitdejBundle:Default:formulairePrestataire }
