ptitdej_homepage:
    path:     /
    defaults: { _controller: PtitdejBundle:Default:index }

form_partenaire:
    path:     /formulaire-partenaire
    defaults: { _controller: PtitdejBundle:Default:formulairePartenaire }

form_entreprise:
    path:     /formulaire-entreprise
    defaults: { _controller: PtitdejBundle:Default:formulaireEntreprise }

form_entreprise_etape2:
    path:     /formulaire-entreprise-etape2
    defaults: { _controller: PtitdejBundle:Default:formulaireEntrepriseEtape2 }

form_prestataire:
    path:     /formulaire-prestataire
    defaults: { _controller: PtitdejBundle:Default:formulairePrestataire }

form_prestataire_etape2:
    path:     /formulaire-prestataire-etape2
    defaults:  {_controller: PtitdejBundle:Default:formulairePrestataireEtape2 }

form_erreur:
    path:     /erreur
    defaults: { _controller: PtitdejBundle:Default:erreur }

ptitdej_contact:
    path:     /qui-sommes-nous
    defaults:  { _controller: PtitdejBundle:Default:pageContact }

form_contact:
    path:     /message-envoye
    defaults:  { _controller: PtitdejBundle:Default:contact }
